# Generated by Django 3.0.8 on 2020-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry_dates', '0002_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='fecha_salida',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
