# Generated by Django 3.0.8 on 2020-08-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expiry_dates', '0003_auto_20200801_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
