# Generated by Django 3.0.8 on 2020-08-12 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expiry_dates', '0006_auto_20200811_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario_elimina',
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_elimina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
