# Generated by Django 3.0.8 on 2020-08-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expiry_dates', '0007_auto_20200811_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
    ]
